### ISSUE TITLE
Few bugs that must be corrected.

### ISSUE THREAD

**Issue by Priyansh2** [irshadbhat/csnli#1]
1. Remove the line `>>> lid = LID()`  from `README.rst` as it creates error. 
2. In the file `three_step_decoding.py` lines 97,98, 99 should be changed to 
`tsd.lid.etrans = tsd.lid.en_trans.trans_dict
 tsd.lid.hi_trans.transliterate('\n'.join(set(io.open(args.tfile).read().split())))
 tsd.lid.htrans = tsd.lid.hi_trans.trans_dict` respectively.
3. Model `kenlm` as requirement should be present in the `requirements.txt`.
4.  `pip install -r requirements.txt` will install only cpu-based dynet but not gpu-based so thats should be changed to as given in its official [doc.](https://dynet.readthedocs.io/en/latest/python.html)

**Comment by irshadbhat** [comment]
Thanks for pointing out these bugs. I have updated the files except for dynet package requirement. 

There won't be any speed enhancements using GPU-based dynet, since the training code doesn't process data in batches and the network parameters are minimal. Using GPU will only introduce additional overhead. I recommend to use CPU-based dynet only.
